services:
  - type: web
    name: clinic-booking-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: gunicorn project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: clinic-booking-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: clinic-booking-db
    plan: free